baseurl = "/"
languageCode = "en-us"
title = "clearip.io"
Subtitle = "Your site's subtitle/tagline"
GithubID = "clearip"
twitter = "getclearip"
AnalyticsID = "Your Google Analytics tracking code"
DisqusShortname = "Your Disqus shortname"
Summary = true  # takes true or false
Content = true  # takes true or false
FooterMsg = "by PushBots Inc 2018"
theme = "hugo-theme-slim"
[params]
twitter = "getclearip"
FullUrl =  "https://clearip.io/"