baseurl = "/"
languageCode = "en-us"
title = "Clearip blog"
Subtitle = "Your site's subtitle/tagline"
GithubID = "clearip"
TwitterID = "clearip"
AnalyticsID = "Your Google Analytics tracking code"
DisqusShortname = "Your Disqus shortname"
Summary = true  # takes true or false
Content = true  # takes true or false
FooterMsg = "Copyright Clearip 2018"
theme = "hugo-theme-slim"